### ISSUE TITLE
{     "kind": "ParserNotFoundError",     "error": "Parser not found for provider 'venusembed.site'" }

### ISSUE THREAD

**Issue by papi028** [WBRK-dev/vidstream-api#2]
tried to get the source for the penquin episode one using both servers buh they all returned this

{
    "kind": "ParserNotFoundError",
    "error": "Parser not found for provider 'venusembed.site'"
}

any reason?

**Comment by WBRK-dev** [comment]
Vidstream recently changed the way video sources get served to visitors.
That means a new source extractor/parser needs to be made.

I will comment here when there is more news on this.

**Comment by papi028** [comment]
> Vidstream recently changed the way video sources get served to visitors. That means a new source extractor/parser needs to be made.
> 
> I will comment here when there is more news on this.

ok i will be checking here again to see the update i wanna implement this api in my  app that why
thanks

**Comment by luismendoza-ec** [comment]
VidStream/VidCloud/UpStream/Embeds etc all of them are the same but now having a different method, hardly protected by a wasm and another obfuscated functions.

I have developed a good solution, you can check in this thread:
https://github.com/drblgn/rabbit_wasm/issues/6#issuecomment-2450376653

**Comment by WBRK-dev** [comment]
@luismendoza-ec 
Thanks for creating a solution.
Does your solution use puppeteer? (I did read your comment but package.json does not include puppeteer as a dependency)

One of my goals for this project is to make the api as lightweight as possible. (for js)
If your solution depends on puppeteer that would mean that some hosting providers can not run the api. (e.g. vercel)

**Comment by luismendoza-ec** [comment]
> @luismendoza-ec Thanks for creating a solution. Does your solution use puppeteer? (I did read your comment but package.json does not include puppeteer as a dependency)
> 
> One of my goals for this project is to make the api as lightweight as possible. (for js) If your solution depends on puppeteer that would mean that some hosting providers can not run the api. (e.g. vercel)

It does, but it’s lightweight. I’m not using Puppeteer to handle requests for intercepting the m3u; instead, I’m running a single sandbox instance to let WebAssembly and other functions handle validations and fingerprinting. All other requests, like fetching embed data, sources, and even the final decryption, happen outside of that instance.

There are more affordable providers for this setup, but it depends on your intended usage. In my case, I have a server running other processes, so I can easily allocate resources for this purpose.

**Comment by WBRK-dev** [comment]
Why I don't like headless browser like extractors is because vercel and other js hosting providers mostly don't let you run those dependencies.
Since there are a lot of people that do not have a home server or vps running and use those hosting providers, there will be people that can not get decrypted sources.

But I can't get over the fact your solution only uses puppeteer as a sandbox, that's really interesting!
I will definitely try your solution!
If this does not work with vercel than that is that.

**Comment by luismendoza-ec** [comment]
Yes, I understand you, but unfortunately, at least for this, you need one instance of Puppeteer; a sandbox that doesn’t require it has not yet been replicated. The validations are stricter and must be performed there at the very least.

Give it a try; I'm sure you'll find a way.

Those who can’t set up the API may be able to consume from others, though it might be free or come at a cost.

**Comment by WBRK-dev** [comment]
Did you release your solution to the public?

**Comment by luismendoza-ec** [comment]
> Did you release your solution to the public?

No, is not released public

**Comment by WBRK-dev** [comment]
Can I get private access to your code?
If I can, we can set some rules for what I can and can't do with it.

**Comment by luismendoza-ec** [comment]
DM on TG @int0x13

**Comment by WBRK-dev** [comment]
This issue is fixed in the latest release.
